name: Windows - Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - ".vscode/**"
      - "README.md"
    branches:
      - main
  pull_request:
    branches:
      - main
#
defaults:
  run:
    shell: bash
#
env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always
  ARTIFACT_NAME: kill_open_programs.exe
#
jobs:
  build-windows:
    name: Build and Release
    runs-on: windows-latest
    #
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      #
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: x86_64-pc-windows-msvc
          default: true
      #
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: windows-cargo-${{ hashFiles('**/Cargo.lock') }}
      #
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      #
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ env.ARTIFACT_NAME }}
          prerelease: false
          draft: true
          name: ${{ env.ARTIFACT_NAME }}_${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          make_latest: true
