name: Tests
on:
  push:
    paths-ignore:
      - ".vscode/**"
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main
#
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
jobs:
  test-windows:
    name: Tests on Windows
    runs-on: windows-latest
    #
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      #
      - name: Install Rust
        uses: actions-rs/toolchain@v2
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: x86_64-pc-windows-msvc
          default: true
      #
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: windows-cargo-${{ hashFiles('**/Cargo.lock') }}
      #
      - name: Run tests
        uses: actions-rs/cargo@v2
        with:
          command: test
          args: --verbose

